import { BarChart3, Building2, Calendar, Loader2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { BalanceSheetTable } from './components/dashboard/BalanceSheetTable';
import { BudgetAnalysis } from './components/dashboard/BudgetAnalysis';
import { BudgetVsActual } from './components/dashboard/BudgetVsActual';
import { CashflowChart } from './components/dashboard/CashflowChart';
import { ExpenseByDepartment } from './components/dashboard/ExpenseByDepartment';
import { FinancialChart } from './components/dashboard/FinancialChart';
import { KpiCard } from './components/dashboard/KpiCard';
import { ProfitLossTable } from './components/dashboard/ProfitLossTable';
import { TopProducts } from './components/dashboard/TopProducts';
import { currentMonth, previousMonth, totalAssets, totalDepartmentExpense, endingCashBalance } from './lib/data/financialDummyData';

const nav = ['Executive Summary','Profit & Loss','Balance Sheet','Cashflow','Gross Margin','Top Products','Expense','Budget'];
const pctChange=(a:number,b:number)=>b===0?0:(a-b)/b;

export function App(){const [loading,setLoading]=useState(false);const [filters,setFilters]=useState({period:'Bulanan',year:'2026',department:'All Department',product:'All Product',entity:'Consolidated'});const kpis=useMemo(()=>[
  ['Total Pendapatan',currentMonth.revenue,pctChange(currentMonth.revenue,previousMonth.revenue),false],['Laba Kotor',currentMonth.grossProfit,pctChange(currentMonth.grossProfit,previousMonth.grossProfit),false],['Laba Bersih',currentMonth.netProfit,pctChange(currentMonth.netProfit,previousMonth.netProfit),false],['Total Asset',totalAssets,0.032,false],['Kas & Bank',endingCashBalance,0.045,false],['Gross Margin',currentMonth.grossMargin,currentMonth.grossMargin-previousMonth.grossMargin,true],['Net Profit Margin',currentMonth.netProfitMargin,currentMonth.netProfitMargin-previousMonth.netProfitMargin,true],['Budget Utilization',totalDepartmentExpense/5030000000,-0.011,true]
] as const,[]);function update(k:string,v:string){setLoading(true);setFilters(f=>({...f,[k]:v}));setTimeout(()=>setLoading(false),350)}return <div className="min-h-screen bg-slate-100 text-slate-900"><aside className="fixed inset-y-0 left-0 hidden w-72 border-r border-slate-200 bg-slate-950 p-6 text-white lg:block"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-600 p-3"><BarChart3/></div><div><h1 className="font-bold">Finance Command</h1><p className="text-xs text-slate-400">Executive Dashboard</p></div></div><nav className="mt-10 space-y-2">{nav.map((n,i)=><a key={n} className={`block rounded-xl px-4 py-3 text-sm ${i===0?'bg-blue-600':'text-slate-300 hover:bg-slate-800'}`} href={`#${n.replaceAll(' ','-')}`}>{n}</a>)}</nav></aside><main className="lg:pl-72"><header className="sticky top-0 z-10 border-b border-slate-200 bg-white/90 px-5 py-4 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-black">Dashboard Keuangan Manajemen</h1><p className="text-sm text-slate-500">Monitor pendapatan, laba, neraca, cashflow, budget, dan varians secara ringkas.</p></div><div className="flex flex-wrap gap-2">{[['period',['Bulanan','Kuartalan','Tahunan']],['year',['2026','2025']],['department',['All Department','Finance','Sales & Marketing','Operations','HR','IT']],['product',['All Product','ERP Subscription','Implementation Service']],['entity',['Consolidated','PT Alpha','PT Beta']]].map(([key,opts])=><select key={key as string} value={(filters as any)[key as string]} onChange={e=>update(key as string,e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm">{(opts as string[]).map(o=><option key={o}>{o}</option>)}</select>)}</div></div></header><div className="space-y-6 p-5 xl:p-8">{loading&&<div className="flex items-center gap-2 rounded-2xl bg-blue-50 p-4 text-blue-700"><Loader2 className="animate-spin"/> Memuat ulang dashboard berdasarkan filter...</div>}<section id="Executive-Summary" className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{kpis.map(([t,v,c,p])=><KpiCard key={t} title={t} value={v} change={c} isPercent={p}/>)}</section><FinancialChart/><ProfitLossTable/><BalanceSheetTable/><CashflowChart/><TopProducts/><ExpenseByDepartment/><BudgetVsActual/><BudgetAnalysis/><section className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><Building2 className="mx-auto text-slate-400"/><h2 className="mt-3 font-bold">Empty State Siap API</h2><p className="text-sm text-slate-500">Jika filter tidak memiliki data, area ini dapat menampilkan pesan kosong dan CTA untuk sinkronisasi database.</p><p className="mt-2 text-xs text-slate-400"><Calendar size={14} className="inline"/> Filter aktif: {Object.values(filters).join(' • ')}</p></section></div></main></div>}
