import React, { useMemo, useState } from './vendor/react.js';

const h = React.createElement;
const pages = [['dashboard', 'Dashboard Utama'], ['neraca', 'Laporan Neraca'], ['laba-rugi', 'Laporan Laba Rugi'], ['budgeting', 'Laporan Budgeting'], ['cashflow', 'Laporan Cashflow']];
const months = [
  ['Jan', 3200, 2050, 1220, 7200, 3300, 3900, 820, 520, 1180], ['Feb', 3450, 2140, 1310, 7420, 3380, 4040, 860, 545, 1495],
  ['Mar', 3820, 2320, 1450, 7780, 3520, 4260, 910, 590, 1815], ['Apr', 4010, 2460, 1525, 8010, 3610, 4400, 945, 620, 2140],
  ['Mei', 4380, 2630, 1660, 8320, 3720, 4600, 980, 655, 2465], ['Jun', 4850, 2890, 1790, 8890, 3920, 4970, 1040, 705, 2800],
  ['Jul', 4720, 2810, 1745, 9020, 3980, 5040, 1010, 690, 3120], ['Agu', 5060, 2990, 1870, 9350, 4100, 5250, 1080, 735, 3465],
  ['Sep', 5280, 3090, 1940, 9610, 4210, 5400, 1120, 760, 3825], ['Okt', 5510, 3210, 2025, 9920, 4350, 5570, 1160, 790, 4195],
  ['Nov', 5740, 3360, 2105, 10180, 4470, 5710, 1210, 820, 4585], ['Des', 6180, 3590, 2260, 10650, 4620, 6030, 1290, 875, 5000],
].map(([month, revenue, expenses, cogs, assets, liabilities, equity, cashIn, cashOut, endingCash]) => ({ month, revenue: revenue * 1000000, expenses: expenses * 1000000, cogs: cogs * 1000000, assets: assets * 1000000, liabilities: liabilities * 1000000, equity: equity * 1000000, cashIn: cashIn * 1000000, cashOut: cashOut * 1000000, endingCash: endingCash * 1000000 }));
const assetComposition = [['Kas & Bank', 2100], ['Piutang', 1750], ['Persediaan', 1270], ['Aset Tetap', 5530]].map(([name, value]) => ({ name, value: value * 1000000 }));
const budgetRows = [['Marketing', 820, 735], ['Operasional Kantor', 510, 424], ['Cloud & Software', 650, 690], ['Training Karyawan', 180, 126], ['Perjalanan Dinas', 260, 258], ['Riset Produk', 430, 382]].map(([category, budget, actual]) => ({ category, budget: budget * 1000000, actual: actual * 1000000 }));
const colors = ['#2563eb', '#0f766e', '#f59e0b', '#7c3aed', '#ef4444', '#14b8a6'];
const safeNumber = (value) => (Number.isFinite(Number(value)) ? Number(value) : 0);
const formatRupiah = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(safeNumber(value));
const netProfit = (month) => safeNumber(month.revenue) - safeNumber(month.expenses);
const usage = (actual, budget) => (budget ? (safeNumber(actual) / safeNumber(budget)) * 100 : 0);
const budgetStatus = (actual, budget) => (usage(actual, budget) > 100 ? 'Over Budget' : usage(actual, budget) >= 80 ? 'Perhatian' : 'Aman');

function App() {
  const [activePage, setActivePage] = useState('dashboard');
  const pageMap = { dashboard: h(Dashboard), neraca: h(BalanceSheet), 'laba-rugi': h(ProfitLoss), budgeting: h(Budgeting), cashflow: h(Cashflow) };
  return h(ErrorBoundary, null, h('div', { className: 'app-shell' },
    h('aside', { className: 'sidebar' }, h('div', { className: 'brand' }, h('div', { className: 'brand-mark' }, 'FA'), h('div', null, h('strong', null, 'Dashboard Finance'), h('span', null, 'Accounting'))),
      h('nav', { 'aria-label': 'Menu laporan keuangan' }, pages.map(([id, label]) => h('button', { key: id, type: 'button', className: id === activePage ? 'nav-link active' : 'nav-link', onClick: () => setActivePage(id) }, label)))),
    h('main', { className: 'content' }, pageMap[activePage] || pageMap.dashboard)));
}
class ErrorBoundary extends React.Component { constructor(p) { super(p); this.state = { error: null }; } static getDerivedStateFromError(error) { return { error }; } render() { return this.state.error ? h('main', { className: 'fallback-page' }, h('h1', null, 'Dashboard Finance Accounting'), h('p', null, 'Aplikasi tetap tampil, tetapi ada komponen yang gagal dirender.'), h('pre', null, this.state.error.message)) : this.props.children; } }
function PageShell({ title, subtitle, children }) { const [period, setPeriod] = useState('Bulanan'); return h(React.Fragment, null, h('header', { className: 'topbar' }, h('div', null, h('p', { className: 'eyebrow' }, 'Dashboard Finance Accounting'), h('h1', null, title), h('p', { className: 'subtitle' }, subtitle)), h('div', { className: 'actions' }, h('select', { value: period, onChange: (e) => setPeriod(e.target.value), 'aria-label': 'Filter periode' }, ['Bulanan', 'Kuartalan', 'Tahunan'].map((p) => h('option', { key: p }, p))), h('button', { type: 'button' }, 'Export PDF'), h('button', { type: 'button' }, 'Export Excel'))), children); }
function KpiCard({ title, value, hint }) { return h('article', { className: 'kpi-card' }, h('span', null, title), h('strong', null, formatRupiah(value)), h('small', null, hint)); }
function ChartCard({ title, children }) { return h('section', { className: 'panel chart-panel' }, h('h2', null, title), h('div', { className: 'chart-box' }, h(ErrorBoundary, null, children))); }
function BarComparison({ data, firstKey, secondKey, firstLabel, secondLabel }) { const max = Math.max(...data.flatMap((d) => [safeNumber(d[firstKey]), safeNumber(d[secondKey])])); return h('div', { className: 'bar-chart' }, data.map((d) => h('div', { className: 'bar-group', key: d.month || d.category, title: `${firstLabel}: ${formatRupiah(d[firstKey])} | ${secondLabel}: ${formatRupiah(d[secondKey])}` }, h('div', { className: 'bars' }, h('span', { style: { height: `${(d[firstKey] / max) * 100}%`, background: colors[0] } }), h('span', { style: { height: `${(d[secondKey] / max) * 100}%`, background: colors[2] } })), h('small', null, d.month || d.category.slice(0, 3))))); }
function LineVisual({ data, dataKey }) { const values = data.map((d) => safeNumber(d[dataKey])); const max = Math.max(...values); const min = Math.min(...values); const points = values.map((v, i) => `${(i / (values.length - 1)) * 100},${90 - ((v - min) / (max - min || 1)) * 75}`).join(' '); return h('svg', { className: 'line-chart', viewBox: '0 0 100 100', preserveAspectRatio: 'none' }, h('polyline', { points, fill: 'none', stroke: '#0f766e', strokeWidth: '3' })); }
function DonutList({ data }) { const total = data.reduce((s, d) => s + d.value, 0); return h('div', { className: 'donut-list' }, data.map((d, i) => h('div', { key: d.name, className: 'donut-row' }, h('span', { style: { background: colors[i % colors.length] } }), h('strong', null, d.name), h('em', null, `${usage(d.value, total).toFixed(1)}%`), h('small', null, formatRupiah(d.value))))); }
function MoneyTable({ rows }) { return h('div', { className: 'table-wrap' }, h('table', null, h('thead', null, h('tr', null, h('th', null, 'Komponen'), h('th', null, 'Nilai'))), h('tbody', null, rows.map(([label, value]) => h('tr', { key: label, className: label.startsWith('Total') || label.includes('Laba') || label.includes('Ending') ? 'total-row' : '' }, h('td', null, label), h('td', { className: 'numeric' }, formatRupiah(value))))))); }
function Dashboard() { const latest = months.at(-1); const totalBudget = budgetRows.reduce((s, b) => s + b.budget, 0); const totalActual = budgetRows.reduce((s, b) => s + b.actual, 0); return h(PageShell, { title: 'Dashboard Utama', subtitle: 'Ringkasan KPI, tren bulanan, dan komposisi keuangan perusahaan.' }, h('section', { className: 'kpi-grid' }, h(KpiCard, { title: 'Total Pendapatan', value: latest.revenue, hint: 'Desember 2026' }), h(KpiCard, { title: 'Total Beban', value: latest.expenses, hint: 'Termasuk HPP & Opex' }), h(KpiCard, { title: 'Laba Bersih', value: netProfit(latest), hint: 'Margin sehat' }), h(KpiCard, { title: 'Total Aset', value: latest.assets, hint: 'Balance sheet' }), h(KpiCard, { title: 'Kas & Bank', value: latest.endingCash, hint: 'Ending cash' }), h(KpiCard, { title: 'Budget Terpakai', value: totalActual, hint: `${usage(totalActual, totalBudget).toFixed(1)}% dari budget` })), h('section', { className: 'grid two-columns' }, h(ChartCard, { title: 'Pendapatan vs Beban per Bulan' }, h(BarComparison, { data: months, firstKey: 'revenue', secondKey: 'expenses', firstLabel: 'Pendapatan', secondLabel: 'Beban' })), h(ChartCard, { title: 'Laba Bersih per Bulan' }, h(LineVisual, { data: months.map((m) => ({ ...m, profit: netProfit(m) })), dataKey: 'profit' })), h(ChartCard, { title: 'Komposisi Aset, Liabilitas, Ekuitas' }, h(DonutList, { data: [{ name: 'Aset', value: latest.assets }, { name: 'Liabilitas', value: latest.liabilities }, { name: 'Ekuitas', value: latest.equity }] })))); }
function BalanceSheet() { const latest = months.at(-1); return h(PageShell, { title: 'Laporan Neraca', subtitle: 'Posisi aset, liabilitas, dan ekuitas dengan struktur balance.' }, h('section', { className: 'grid two-columns' }, h('section', { className: 'panel' }, h('h2', null, 'Tabel Aset, Liabilitas, dan Ekuitas'), h(MoneyTable, { rows: [['Aset Lancar', 5120000000], ['Aset Tetap', 5530000000], ['Total Aset', latest.assets], ['Liabilitas', latest.liabilities], ['Ekuitas', latest.equity], ['Total Liabilitas + Ekuitas', latest.liabilities + latest.equity]] })), h(ChartCard, { title: 'Grafik Komposisi Aset' }, h(DonutList, { data: assetComposition })))); }
function ProfitLoss() { const latest = months.at(-1); const marginData = useMemo(() => months.map((m) => ({ month: m.month, margin: (netProfit(m) / m.revenue) * 100 })), []); return h(PageShell, { title: 'Laporan Laba Rugi', subtitle: 'Pendapatan, HPP, beban, laba bersih, dan margin profitabilitas.' }, h('section', { className: 'grid two-columns' }, h('section', { className: 'panel' }, h('h2', null, 'Tabel Laba Rugi'), h(MoneyTable, { rows: [['Pendapatan', latest.revenue], ['Harga Pokok Penjualan', latest.cogs], ['Laba Kotor', latest.revenue - latest.cogs], ['Beban Operasional', latest.expenses - latest.cogs], ['Laba Bersih', netProfit(latest)]] })), h(ChartCard, { title: 'Pendapatan vs Beban' }, h(BarComparison, { data: months, firstKey: 'revenue', secondKey: 'expenses', firstLabel: 'Pendapatan', secondLabel: 'Beban' })), h(ChartCard, { title: 'Margin Laba Bersih' }, h(LineVisual, { data: marginData, dataKey: 'margin' })))); }
function Budgeting() { return h(PageShell, { title: 'Laporan Budgeting', subtitle: 'Monitoring budget vs actual lengkap dengan status Aman, Perhatian, dan Over Budget.' }, h('section', { className: 'grid two-columns' }, h('section', { className: 'panel wide' }, h('h2', null, 'Tabel Budget vs Actual'), h('div', { className: 'table-wrap' }, h('table', null, h('thead', null, h('tr', null, ['Kategori', 'Budget', 'Actual', 'Selisih', 'Pemakaian', 'Status'].map((c) => h('th', { key: c }, c)))), h('tbody', null, budgetRows.map((b) => { const status = budgetStatus(b.actual, b.budget); return h('tr', { key: b.category }, h('td', null, b.category), h('td', { className: 'numeric' }, formatRupiah(b.budget)), h('td', { className: 'numeric' }, formatRupiah(b.actual)), h('td', { className: 'numeric' }, formatRupiah(b.budget - b.actual)), h('td', { className: 'numeric' }, `${usage(b.actual, b.budget).toFixed(1)}%`), h('td', null, h('span', { className: `status ${status.toLowerCase().replace(' ', '-')}` }, status))); }))))), h(ChartCard, { title: 'Grafik Budget vs Actual' }, h(BarComparison, { data: budgetRows, firstKey: 'budget', secondKey: 'actual', firstLabel: 'Budget', secondLabel: 'Actual' })))); }
function Cashflow() { const latest = months.at(-1); const previous = months.at(-2); return h(PageShell, { title: 'Laporan Cashflow', subtitle: 'Arus kas masuk, keluar, net cashflow, opening balance, dan ending balance.' }, h('section', { className: 'grid two-columns' }, h('section', { className: 'panel' }, h('h2', null, 'Ringkasan Cashflow'), h(MoneyTable, { rows: [['Cash Inflow', latest.cashIn], ['Cash Outflow', latest.cashOut], ['Net Cashflow', latest.cashIn - latest.cashOut], ['Opening Balance', previous.endingCash], ['Ending Balance', latest.endingCash]] })), h(ChartCard, { title: 'Grafik Cash Inflow vs Cash Outflow' }, h(BarComparison, { data: months, firstKey: 'cashIn', secondKey: 'cashOut', firstLabel: 'Cash Inflow', secondLabel: 'Cash Outflow' })), h(ChartCard, { title: 'Grafik Ending Cash Balance' }, h(LineVisual, { data: months, dataKey: 'endingCash' })))); }
export default App;
