import React, { useMemo, useState } from "./vendor/react.js";

const h = React.createElement;
const months = ["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
const departments = ["Finance","Accounting","Marketing","Operational","Human Resources","Information Technology","General Affairs"];
const categories = ["Gaji dan Tunjangan","Marketing","Sewa","Utilitas","Transportasi","Peralatan","Perawatan","Biaya Operasional Lainnya"];
const menus = ["Dashboard","Budget vs Aktual","Detail Budget","Realisasi","Analisis Over Budget","Upload Data","Pengaturan"];
const icons = ["▦","⇄","▤","✓","⚠","⇧","⚙"];
const rp = value => new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number.isFinite(value)?value:0);
const pct = value => `${(Number.isFinite(value)?value:0).toFixed(1)}%`;
const ratio = (actual,budget) => budget>0 ? actual/budget*100 : 0;
const status = (actual,budget) => actual>budget ? "Over Budget" : ratio(actual,budget)>=80 ? "Perhatian" : "Aman";
const cls = value => String(value).toLowerCase().replaceAll(" ","-");

const budgets = Array.from({length:48},(_,i)=>{
  const month=i%12, dept=departments[i%7], category=categories[(i*3)%8];
  const budget=(28+(i%9)*7)*1000000;
  const factor=[.62,.76,.84,.93,1.08,1.17][i%6];
  return {id:`BDG-${2026001+i}`,year:2026,month:months[month],monthIndex:month+1,department:dept,category,code:`BG-${String(i+1).padStart(3,"0")}`,name:`${category} ${dept}`,budget,actual:Math.round(budget*factor),owner:["Ayu Pratiwi","Budi Santoso","Citra Lestari","Dimas Putra"][i%4],note:i%6>3?"Evaluasi harga vendor":"Sesuai rencana kerja"};
});
const transactions = Array.from({length:60},(_,i)=>{const b=budgets[i%48];return {id:`TRX-2026-${String(i+1).padStart(4,"0")}`,date:`2026-${String(i%12+1).padStart(2,"0")}-${String(i%27+1).padStart(2,"0")}`,department:b.department,category:b.category,description:`Pembayaran ${b.category.toLowerCase()}`,actual:Math.round(b.actual/(1+(i%3))),reference:`INV/${String(i+81).padStart(4,"0")}`,vendor:["PT Nusantara Jaya","CV Solusi Prima","PT Karya Digital","Internal"][i%4],budget:b.code,match:["Sudah Masuk Budget","Sudah Masuk Budget","Perlu Pemeriksaan","Belum Masuk Budget"][i%4]};});

function Badge({children}){return h("span",{className:`badge ${cls(children)}`},children)}
function Button({children,onClick,kind="secondary",type="button"}){return h("button",{className:`btn ${kind}`,onClick,type},children)}
function Card({title,subtitle,children,className=""}){return h("section",{className:`card ${className}`},title&&h("div",{className:"card-head"},h("div",null,h("h2",null,title),subtitle&&h("p",null,subtitle)),h("button",{className:"more"},"•••")),children)}
function Empty(){return h("div",{className:"empty"},h("b",null,"Data tidak ditemukan"),h("span",null,"Ubah filter atau kata kunci untuk melihat data."))}
function Kpis({data=budgets}){const budget=data.reduce((s,x)=>s+x.budget,0),actual=data.reduce((s,x)=>s+x.actual,0),over=data.filter(x=>x.actual>x.budget).length,safe=data.filter(x=>ratio(x.actual,x.budget)<80).length;const items=[["Total Budget",rp(budget),"wallet","12 bulan"],["Total Aktual",rp(actual),"chart",pct(ratio(actual,budget))],["Sisa Budget",rp(budget-actual),"coin",budget>=actual?"Tersedia":"Defisit"],["Penggunaan",pct(ratio(actual,budget)),"trend","dari total budget"],["Over Budget",String(over),"alert","perlu tindakan"],["Budget Aman",String(safe),"check","di bawah 80%"]];return h("div",{className:"kpi-grid"},items.map(([label,value,icon,hint],i)=>h("article",{className:`card kpi kpi-${i}`,key:label},h("div",{className:`kpi-icon ${icon}`},["◫","◩","◉","↗","!","✓"][i]),h("span",null,label),h("strong",null,value),h("small",null,h("i",null,i===4?"↑":"●"),hint))))}
function BarChart({data,horizontal=false}){
  const max=Math.max(1,...data.flatMap(x=>[x.budget,x.actual]));
  if(!data.length)return h(Empty);
  if(horizontal)return h("div",{className:"hbars"},data.map(x=>h("div",{className:"hbar-row",key:x.name},h("span",null,x.name),h("div",{className:"tracks"},h("i",{className:"track budget-bar",style:{width:`${x.budget/max*100}%`}}),h("i",{className:"track actual-bar",style:{width:`${x.actual/max*100}%`}})),h("b",null,pct(ratio(x.actual,x.budget))))));
  return h("div",{className:"bars"},data.map(x=>h("div",{className:"bar-item",key:x.name},h("div",{className:"columns"},h("i",{className:"column budget-bar",style:{height:`${x.budget/max*100}%`}}),h("i",{className:"column actual-bar",style:{height:`${x.actual/max*100}%`}})),h("span",null,x.name.slice(0,3)))));
}
function Legend(){return h("div",{className:"legend"},h("span",null,h("i",{className:"blue-dot"}),"Budget"),h("span",null,h("i",{className:"green-dot"}),"Aktual"))}
function Donut({data}){const total=data.reduce((s,x)=>s+x.actual,0);let run=0;const stops=data.map((x,i)=>{const start=run;run+=total?x.actual/total*100:0;return `var(--c${i%8}) ${start}% ${run}%`}).join(",");return h("div",{className:"donut-wrap"},h("div",{className:"donut",style:{background:`conic-gradient(${stops})`}},h("div",null,h("small",null,"Total Aktual"),h("b",null,rp(total)))),h("div",{className:"donut-legend"},data.map((x,i)=>h("div",{key:x.name},h("i",{style:{background:`var(--c${i%8})`}}),h("span",null,x.name),h("b",null,pct(total?x.actual/total*100:0))))))}
function group(data,key){return Object.values(data.reduce((a,x)=>{const n=x[key];a[n]??={name:n,budget:0,actual:0};a[n].budget+=x.budget;a[n].actual+=x.actual;return a},{}))}
function GlobalFilters({filters,setFilters}){const select=(key,values,label)=>h("label",null,h("span",null,label),h("select",{value:filters[key],onChange:e=>setFilters({...filters,[key]:e.target.value})},h("option",{value:"Semua"},`Semua ${label}`),values.map(x=>h("option",{key:x},x))));return h("div",{className:"global-filter"},select("year",["2026"],"Tahun"),select("month",months,"Bulan"),select("department",departments,"Departemen"),select("category",categories,"Kategori"),h(Button,{onClick:()=>setFilters({year:"2026",month:"Semua",department:"Semua",category:"Semua"})},"Atur Ulang"))}
function MonitoringTable({data}){const [search,setSearch]=useState(""),[page,setPage]=useState(1),[sort,setSort]=useState("budget");const filtered=data.filter(x=>`${x.department} ${x.category} ${x.name}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b[sort]-a[sort]);const shown=filtered.slice((page-1)*8,page*8);return h(Card,{title:"Monitoring Budget",subtitle:"Pantau realisasi dan status setiap alokasi budget"},h("div",{className:"table-tools"},h("div",{className:"search"},"⌕",h("input",{value:search,onChange:e=>{setSearch(e.target.value);setPage(1)},placeholder:"Cari budget, departemen, kategori..."})),h("select",{value:sort,onChange:e=>setSort(e.target.value)},h("option",{value:"budget"},"Urutkan: Budget"),h("option",{value:"actual"},"Urutkan: Aktual"))),h("div",{className:"table-scroll"},h("table",null,h("thead",null,h("tr",null,["Periode","Departemen","Kategori / Budget","Nilai Budget","Nilai Aktual","Selisih","Penggunaan","Status","Catatan"].map(x=>h("th",{key:x},x)))),h("tbody",null,shown.length?shown.map(x=>h("tr",{key:x.id},h("td",null,x.month," 2026"),h("td",null,h("b",null,x.department)),h("td",null,h("b",null,x.name),h("small",null,x.category)),h("td",null,rp(x.budget)),h("td",null,rp(x.actual)),h("td",{className:x.budget-x.actual<0?"negative":"positive"},rp(x.budget-x.actual)),h("td",null,h("div",{className:"usage"},h("span",null,pct(ratio(x.actual,x.budget))),h("i",null,h("b",{style:{width:`${Math.min(100,ratio(x.actual,x.budget))}%`}})))),h("td",null,h(Badge,null,status(x.actual,x.budget))),h("td",null,x.note))):h("tr",null,h("td",{colSpan:9},h(Empty)))))),h("div",{className:"pagination"},h("span",null,`Menampilkan ${shown.length} dari ${filtered.length} data`),h("div",null,h(Button,{onClick:()=>setPage(Math.max(1,page-1))},"‹"),h("b",null,page),h(Button,{onClick:()=>setPage(Math.min(Math.ceil(filtered.length/8)||1,page+1))},"›"))))}
function Dashboard({data}){const monthly=months.map(name=>group(data.filter(x=>x.month===name),"month")[0]||{name,budget:0,actual:0});const dept=group(data,"department"),cat=group(data,"category");const warnings=data.filter(x=>ratio(x.actual,x.budget)>=90).slice(0,3);return h(React.Fragment,null,h(Kpis,{data}),h("div",{className:"warnings"},warnings.map((x,i)=>h("div",{className:`warning ${x.actual>x.budget?"red":"orange"}`,key:x.id},h("b",null,x.actual>x.budget?"!":"⚠"),h("span",null,h("strong",null,x.name),` telah digunakan ${pct(ratio(x.actual,x.budget))}. Sisa budget ${rp(Math.max(0,x.budget-x.actual))}.`),h("button",null,"×")))),h("div",{className:"grid two"},h(Card,{title:"Budget vs Aktual per Bulan",subtitle:"Perbandingan alokasi dan realisasi tahun 2026"},h(BarChart,{data:monthly}),h(Legend)),h(Card,{title:"Komposisi Penggunaan Budget",subtitle:"Berdasarkan kategori biaya"},h(Donut,{data:cat}))),h("div",{className:"grid two"},h(Card,{title:"Budget per Departemen",subtitle:"Persentase penggunaan per unit",className:"wide-chart"},h(BarChart,{data:dept,horizontal:true})),h(Card,{title:"Tren Penggunaan Budget",subtitle:"Budget, aktual, dan persentase bulanan"},h("div",{className:"trend-chart"},h("svg",{viewBox:"0 0 600 220",preserveAspectRatio:"none"},h("polyline",{points:monthly.map((x,i)=>`${i*54+4},${205-x.budget/1000000}`).join(" "),className:"line budget-line"}),h("polyline",{points:monthly.map((x,i)=>`${i*54+4},${205-x.actual/1000000}`).join(" "),className:"line actual-line"}))),h(Legend))),h(MonitoringTable,{data}))}
function SimpleTable({headers,rows}){return h("div",{className:"table-scroll"},h("table",null,h("thead",null,h("tr",null,headers.map(x=>h("th",{key:x},x)))),h("tbody",null,rows.length?rows:h("tr",null,h("td",{colSpan:headers.length},h(Empty))))))}
function BudgetVsActual({data}){const dept=group(data,"department"),cat=group(data,"category"),monthly=months.map(name=>group(data.filter(x=>x.month===name),"month")[0]||{name,budget:0,actual:0});return h(React.Fragment,null,h(Kpis,{data}),h("div",{className:"grid two"},h(Card,{title:"Perbandingan per Bulan"},h(BarChart,{data:monthly}),h(Legend)),h(Card,{title:"Perbandingan per Departemen"},h(BarChart,{data:dept,horizontal:true}))),h(Card,{title:"Perbandingan per Kategori Biaya"},h(BarChart,{data:cat,horizontal:true})))}
function DetailBudget({data,setData}){const [modal,setModal]=useState(false),[edit,setEdit]=useState(null);const remove=id=>setData(data.filter(x=>x.id!==id));const open=x=>{setEdit(x||null);setModal(true)};const save=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),base=edit||budgets[0];const next={...base,id:edit?.id||`BDG-${Date.now()}`,name:fd.get("name"),budget:Number(fd.get("budget"))||0};setData(edit?data.map(x=>x.id===edit.id?next:x):[next,...data]);setModal(false)};return h(React.Fragment,null,h("div",{className:"page-actions"},h(Button,{kind:"primary",onClick:()=>open()},"＋ Tambah Budget")),h(Card,{title:"Daftar Detail Budget",subtitle:"Kelola master budget tahun berjalan"},h(SimpleTable,{headers:["Tahun","Bulan","Departemen","Kategori","Kode","Deskripsi","Nilai Budget","Penanggung Jawab","Status","Aksi"],rows:data.slice(0,20).map(x=>h("tr",{key:x.id},h("td",null,x.year),h("td",null,x.month),h("td",null,x.department),h("td",null,x.category),h("td",null,x.code),h("td",null,x.name),h("td",null,rp(x.budget)),h("td",null,x.owner),h("td",null,h(Badge,null,"Aktif")),h("td",{className:"row-actions"},h("button",{onClick:()=>open(x)},"Edit"),h("button",{onClick:()=>alert(`${x.name}\n${rp(x.budget)}`)},"Detail"),h("button",{className:"delete",onClick:()=>remove(x.id)},"Hapus"))))})),modal&&h("div",{className:"modal-backdrop",onClick:()=>setModal(false)},h("form",{className:"modal",onSubmit:save,onClick:e=>e.stopPropagation()},h("div",{className:"modal-title"},h("h2",null,edit?"Edit Budget":"Tambah Budget"),h("button",{type:"button",onClick:()=>setModal(false)},"×")),h("label",null,h("span",null,"Deskripsi Budget"),h("input",{name:"name",required:true,defaultValue:edit?.name||""})),h("label",null,h("span",null,"Nilai Budget"),h("input",{name:"budget",type:"number",min:0,required:true,defaultValue:edit?.budget||""})),h("div",{className:"modal-actions"},h(Button,{onClick:()=>setModal(false)},"Batal"),h(Button,{type:"submit",kind:"primary"},"Simpan Budget"))))) }
function Realisasi(){return h(Card,{title:"Transaksi Realisasi",subtitle:"Daftar transaksi aktual dan status pencocokan budget"},h(SimpleTable,{headers:["Tanggal","Nomor Transaksi","Departemen","Kategori","Deskripsi","Nilai Aktual","Referensi","Vendor","Budget Terkait","Status Pencocokan"],rows:transactions.slice(0,30).map(x=>h("tr",{key:x.id},h("td",null,x.date),h("td",null,h("b",null,x.id)),h("td",null,x.department),h("td",null,x.category),h("td",null,x.description),h("td",null,rp(x.actual)),h("td",null,x.reference),h("td",null,x.vendor),h("td",null,x.budget),h("td",null,h(Badge,null,x.match))))}))}
function OverBudget({data}){
  const over=data.filter(x=>x.actual>x.budget);
  const rows=over.map(x=>h("tr",{key:x.id},h("td",null,x.department),h("td",null,x.category),h("td",null,h("b",null,x.name)),h("td",null,rp(x.budget)),h("td",null,rp(x.actual)),h("td",{className:"negative"},rp(x.actual-x.budget)),h("td",null,h(Badge,null,pct(ratio(x.actual-x.budget,x.budget)))),h("td",null,"Kenaikan harga / kebutuhan tambahan"),h("td",null,"Review dan realokasi budget")));
  return h(React.Fragment,null,
    h("div",{className:"analysis-summary"},h("b",null,"Analisis Otomatis"),h("p",null,`${over.length} budget melebihi batas. Mayoritas dipicu kenaikan harga vendor dan kebutuhan operasional di luar rencana.`),h("ul",null,h("li",null,"Pengeluaran melebihi budget lebih dari 10% pada beberapa pos."),h("li",null,"Terdapat transaksi yang perlu dicocokkan dengan budget."),h("li",null,"Lakukan realokasi dan negosiasi ulang dengan vendor."))),
    h(Card,{title:"Daftar Over Budget",subtitle:"Prioritas tindak lanjut Finance Accounting"},h(SimpleTable,{headers:["Departemen","Kategori","Nama Budget","Budget","Aktual","Nilai Over","Persentase Over","Penyebab","Rencana Tindakan"],rows}))
  );
}
function Upload(){const [type,setType]=useState("Master Budget"),[rows,setRows]=useState([]);const change=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).split(/\r?\n/).filter(Boolean).slice(0,8);setRows(lines.map((line,i)=>({line:i+1,values:line.split(","),valid:i>0&&line.split(",").length>=4}))) };reader.readAsText(file)};return h(React.Fragment,null,h("div",{className:"upload-types"},["Master Budget","Data Aktual","Master Departemen","Master Kategori"].map(x=>h("button",{className:type===x?"selected":"",onClick:()=>setType(x),key:x},x))),h(Card,{title:`Upload ${type}`,subtitle:"Format Excel (.xlsx) atau CSV, maksimum 10 MB"},h("label",{className:"dropzone"},h("b",null,"⇧"),h("strong",null,"Tarik file ke sini atau klik untuk memilih"),h("span",null,"Data akan divalidasi sebelum disimpan"),h("input",{type:"file",accept:".csv,.xlsx",onChange:change}))),rows.length>0&&h(Card,{title:"Preview & Hasil Validasi"},h("div",{className:"upload-stats"},h("span",null,h("b",null,rows.filter(x=>x.valid).length)," Baris berhasil"),h("span",null,h("b",null,rows.filter(x=>!x.valid).length)," Baris gagal"),h("span",null,h("b",null,"0")," Duplikat")),h(SimpleTable,{headers:["Baris","Preview Data","Status","Pesan"],rows:rows.map(x=>h("tr",{key:x.line},h("td",null,x.line),h("td",null,x.values.join(" · ")),h("td",null,h(Badge,null,x.valid?"Valid":"Error")),h("td",null,x.valid?"Siap disimpan":"Kolom wajib belum lengkap")))}),h("div",{className:"page-actions"},h(Button,{kind:"primary",onClick:()=>alert("Data valid berhasil disimpan sementara.")},"Simpan Data Valid"))))}
function Settings(){return h("div",{className:"grid two"},h(Card,{title:"Preferensi Dashboard"},h("div",{className:"settings"},h("label",null,h("span",null,"Mata Uang"),h("select",null,h("option",null,"Rupiah (IDR)"))),h("label",null,h("span",null,"Ambang Peringatan"),h("select",null,h("option",null,"80% — Perhatian"))),h(Button,{kind:"primary",onClick:()=>alert("Pengaturan berhasil disimpan.")},"Simpan Pengaturan"))),h(Card,{title:"Informasi Sistem"},h("dl",{className:"info-list"},h("div",null,h("dt",null,"Versi"),h("dd",null,"1.0.0")),h("div",null,h("dt",null,"Penyimpanan"),h("dd",null,"State aplikasi")),h("div",null,h("dt",null,"Tahun Fiskal"),h("dd",null,"2026")))))}
export default function App(){const [active,setActive]=useState("Dashboard"),[mobile,setMobile]=useState(false),[data,setData]=useState(budgets),[filters,setFilters]=useState({year:"2026",month:"Semua",department:"Semua",category:"Semua"});const filtered=useMemo(()=>data.filter(x=>(filters.month==="Semua"||x.month===filters.month)&&(filters.department==="Semua"||x.department===filters.department)&&(filters.category==="Semua"||x.category===filters.category)),[data,filters]);const pages={"Dashboard":h(Dashboard,{data:filtered}),"Budget vs Aktual":h(BudgetVsActual,{data:filtered}),"Detail Budget":h(DetailBudget,{data:filtered,setData}),"Realisasi":h(Realisasi),"Analisis Over Budget":h(OverBudget,{data:filtered}),"Upload Data":h(Upload),"Pengaturan":h(Settings)};return h("div",{className:"app-shell"},h("aside",{className:`sidebar ${mobile?"open":""}`},h("div",{className:"brand"},h("div",{className:"brandmark"},"F"),h("div",null,h("b",null,"Finora"),h("span",null,"FINANCE CONTROL"))),h("nav",null,menus.map((x,i)=>h("button",{className:active===x?"active":"",onClick:()=>{setActive(x);setMobile(false)},key:x},h("i",null,icons[i]),h("span",null,x)))),h("div",{className:"user"},h("div",null,"AP"),h("span",null,h("b",null,"Andi Pratama"),h("small",null,"Finance Manager")),h("button",null,"⋮"))),h("main",null,h("header",{className:"topbar"},h("button",{className:"mobile-menu",onClick:()=>setMobile(!mobile)},"☰"),h("div",null,h("p",null,"FINANCE ACCOUNTING"),h("h1",null,active),h("span",null,"Periode laporan: Januari – Desember 2026")),h("div",{className:"header-actions"},h("span",null,"Terakhir diperbarui",h("b",null,"Hari ini, 09:42")),h(Button,{onClick:()=>location.reload()},"↻ Refresh"),h(Button,{kind:"primary",onClick:()=>setActive("Upload Data")},"⇧ Upload Data"))),h(GlobalFilters,{filters,setFilters}),h("div",{className:"page"},pages[active])))}
